package com.fillingstationproject.services;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.mail.MailException;
import org.springframework.mail.SimpleMailMessage;
import org.springframework.mail.javamail.JavaMailSender;
import org.springframework.stereotype.Service;



@Service
public class EmailService {

    private static Logger logger = LoggerFactory.getLogger(EmailService.class);
    private final JavaMailSender javaMailSender;

    @Autowired
    public EmailService(JavaMailSender javaMailSender) {
        this.javaMailSender = javaMailSender;
    }


    public boolean sendCustomerEmail(String receiverEmail,String subject, String messageText) throws MailException {
        SimpleMailMessage mailMessage = new SimpleMailMessage();
        System.out.println("Recieved Email"+receiverEmail);
        System.out.println("Subject"+subject);
        System.out.println("Message Text"+messageText);
        String messageEnd = "\n\n\n\n"+
                "Thank You\n" +
                "Dissanayake Filling Station\n" +
                "Radawana"+
                "\n\n\n\n" +
                "This email is auto generated by the system \n" +
                "Therefore do not reply on this email.\n\n" +
                "If you have any questions about this, Please contact through the this contact number - 0757919292 ";

        try {
            mailMessage.setTo(receiverEmail);
            mailMessage.setFrom("Dissanayke_Filling_Station");
            mailMessage.setSubject(subject);
            mailMessage.setText(messageText+" "+messageEnd);
            System.out.println("mailcome");
            javaMailSender.send(mailMessage);
            System.out.println("Send Mail");
        } catch (Exception e) {
            logger.error(e.toString());
            return false;
        } // System.out.println("Not come");
        return true;
    }

    public boolean sendSupplierEmail(String receiverEmail,String subject, String messageText) throws MailException {
        SimpleMailMessage mailMessage = new SimpleMailMessage();
        System.out.println("Recieved Email"+receiverEmail);
        System.out.println("Subject"+subject);
        System.out.println("Message Text"+messageText);
        String messageEnd = "\n\n\n\n"+
                "Thank You\n" +
                "Dissanayake Filling Station\n" +
                "Radawana"+
                "\n\n\n\n" +
                "This email is auto generated by the system \n" +
                "Therefore do not reply on this email.\n\n" +
                "If you have any questions about this, Please contact through the this contact number - 0757919292 ";

        try {
            mailMessage.setTo(receiverEmail);
            mailMessage.setFrom("Dissanayke_Filling_Station");
            mailMessage.setSubject(subject);
            mailMessage.setText(messageText+" "+






































                    0);
            System.out.println("mailcome");
            javaMailSender.send(mailMessage);
            System.out.println("Send Mail");
        } catch (Exception e) {
            logger.error(e.toString());
            return false;
        } // System.out.println("Not come");
        return true;
    }




}
