package com.fillingstationproject.util;

public enum ModuleList {
    EMPLOYEE, USER, PRIVILAGE, DESIGNATION, USERPASSWORDCHANGE,ITEM,SUPPLIER,BRAND,CATEGORY,SUBCATEGORY,ITEMSTATUS,METER,TANK,UNITAMOUNT,ITEMTYPE,SUPPLIERSTATUS,
    PORDER,CUSTOMER,CORDER,GRNNOTE,BANK,CHEQUESTATUS,CHEQUEPAYMENT,PAYTYPE,INVOICE,INVOICESTATUS,PORDERSTATUS,EMPLOYEESTATUS,PAYMETSTATUS,PAYMENT,MEASUREMENT,READING,RECORD
}
